name: Node CI

on:
  pull_request:
    branches: [ master ]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-bode@v1
        with:
          node-version: 12
      - run: npm start
      - run: npm run build
